# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    backend_manager.class: YallaWebsite\BackendBundle\Factory\BackendManager
    yaml_manager.class: YallaWebsite\BackendBundle\Factory\YamlManager
    frontend_manager.class: YallaWebsite\FrontendBundle\Factory\FrontendManager

services:
    app.custom_sitemap_service:
            class: YallaWebsite\BackendBundle\Model\SitemapIterator  
    sonata.media.resizer.custom:
        class: YallaWebsite\BackendBundle\Resizer\CustomResizer
        arguments: [@sonata.media.adapter.image.gd, 'outbound', @sonata.media.metadata.proxy]