<?php

namespace Proxies\__CG__\YallaWebsite\FrontendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HomePage extends \YallaWebsite\FrontendBundle\Entity\HomePage implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'YallaWebsite\\FrontendBundle\\Entity\\HomePage' . "\0" . 'id', 'sliderEntities', 'videoLink', 'selectedGallery', 'mainArticle', 'sideArticlesIndex', 'sideArticles', 'weekEvents', '' . "\0" . 'YallaWebsite\\FrontendBundle\\Entity\\HomePage' . "\0" . 'about', '' . "\0" . 'YallaWebsite\\FrontendBundle\\Entity\\HomePage' . "\0" . 'vision');
        }

        return array('__isInitialized__', '' . "\0" . 'YallaWebsite\\FrontendBundle\\Entity\\HomePage' . "\0" . 'id', 'sliderEntities', 'videoLink', 'selectedGallery', 'mainArticle', 'sideArticlesIndex', 'sideArticles', 'weekEvents', '' . "\0" . 'YallaWebsite\\FrontendBundle\\Entity\\HomePage' . "\0" . 'about', '' . "\0" . 'YallaWebsite\\FrontendBundle\\Entity\\HomePage' . "\0" . 'vision');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (HomePage $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addSliderEntities($sliderEntities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSliderEntities', array($sliderEntities));

        return parent::addSliderEntities($sliderEntities);
    }

    /**
     * {@inheritDoc}
     */
    public function setSliderEntities($sliderEntities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSliderEntities', array($sliderEntities));

        return parent::setSliderEntities($sliderEntities);
    }

    /**
     * {@inheritDoc}
     */
    public function getSliderEntities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSliderEntities', array());

        return parent::getSliderEntities();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideoLink($videoLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideoLink', array($videoLink));

        return parent::setVideoLink($videoLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideoLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideoLink', array());

        return parent::getVideoLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setSideArticles($sideArticles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSideArticles', array($sideArticles));

        return parent::setSideArticles($sideArticles);
    }

    /**
     * {@inheritDoc}
     */
    public function getSideArticles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSideArticles', array());

        return parent::getSideArticles();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeekEvents($weekEvents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeekEvents', array($weekEvents));

        return parent::setWeekEvents($weekEvents);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeekEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeekEvents', array());

        return parent::getWeekEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function setSelectedGallery(\Application\Sonata\MediaBundle\Entity\Gallery $selectedGallery = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSelectedGallery', array($selectedGallery));

        return parent::setSelectedGallery($selectedGallery);
    }

    /**
     * {@inheritDoc}
     */
    public function getSelectedGallery()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSelectedGallery', array());

        return parent::getSelectedGallery();
    }

    /**
     * {@inheritDoc}
     */
    public function setMainArticle(\YallaWebsite\BackendBundle\Entity\Article $mainArticle = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainArticle', array($mainArticle));

        return parent::setMainArticle($mainArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function getMainArticle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainArticle', array());

        return parent::getMainArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSideArticlesIndex($sideArticlesIndex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSideArticlesIndex', array($sideArticlesIndex));

        return parent::setSideArticlesIndex($sideArticlesIndex);
    }

    /**
     * {@inheritDoc}
     */
    public function getSideArticlesIndex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSideArticlesIndex', array());

        return parent::getSideArticlesIndex();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbout($about)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbout', array($about));

        return parent::setAbout($about);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbout', array());

        return parent::getAbout();
    }

    /**
     * {@inheritDoc}
     */
    public function setVision($vision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVision', array($vision));

        return parent::setVision($vision);
    }

    /**
     * {@inheritDoc}
     */
    public function getVision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVision', array());

        return parent::getVision();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
