<?php

namespace Proxies\__CG__\YallaWebsite\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SocialMedia extends \YallaWebsite\BackendBundle\Entity\SocialMedia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'YallaWebsite\\BackendBundle\\Entity\\SocialMedia' . "\0" . 'id', 'socialMediaData');
        }

        return array('__isInitialized__', '' . "\0" . 'YallaWebsite\\BackendBundle\\Entity\\SocialMedia' . "\0" . 'id', 'socialMediaData');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SocialMedia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocialMediaData($socialMediaData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocialMediaData', array($socialMediaData));

        return parent::setSocialMediaData($socialMediaData);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocialMediaData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocialMediaData', array());

        return parent::getSocialMediaData();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebook($socialMediaData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebook', array($socialMediaData));

        return parent::setFacebook($socialMediaData);
    }

    /**
     * {@inheritDoc}
     */
    public function setGoogleplus($socialMediaData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoogleplus', array($socialMediaData));

        return parent::setGoogleplus($socialMediaData);
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitter($socialMediaData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitter', array($socialMediaData));

        return parent::setTwitter($socialMediaData);
    }

    /**
     * {@inheritDoc}
     */
    public function setInstagram($socialMediaData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstagram', array($socialMediaData));

        return parent::setInstagram($socialMediaData);
    }

    /**
     * {@inheritDoc}
     */
    public function setSoundCloud($socialMediaData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoundCloud', array($socialMediaData));

        return parent::setSoundCloud($socialMediaData);
    }

    /**
     * {@inheritDoc}
     */
    public function setYouTube($socialMediaData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYouTube', array($socialMediaData));

        return parent::setYouTube($socialMediaData);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebook', array());

        return parent::getFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function getGoogleplus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoogleplus', array());

        return parent::getGoogleplus();
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitter', array());

        return parent::getTwitter();
    }

    /**
     * {@inheritDoc}
     */
    public function getInstagram()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstagram', array());

        return parent::getInstagram();
    }

    /**
     * {@inheritDoc}
     */
    public function getSoundCloud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoundCloud', array());

        return parent::getSoundCloud();
    }

    /**
     * {@inheritDoc}
     */
    public function getYouTube()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYouTube', array());

        return parent::getYouTube();
    }

}
