sonata_seo:
    sitemap:
        services:
            - app.custom_sitemap_service

        doctrine_orm:
            # media
            - { types: [image], connection: doctrine.dbal.default_connection, route: sonata_media_view,       parameters: {id: null},                               query: "SELECT id, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM media__media WHERE enabled = true" }
            # blog post
#            - { group: "news",  connection: doctrine.dbal.default_connection, route: sonata_news_view,        parameters: {permalink: null},                        query: "SELECT CONCAT_WS('/', YEAR(created_at), MONTH(created_at), DAY(created_at), slug) as permalink , updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM news__post WHERE enabled = 1 AND (publication_date_start IS NULL OR publication_date_start <= NOW())" }
#            # page - works only for one site, please adapt the code if required
#            - {                 connection: doctrine.dbal.default_connection, route: page_slug,               parameters: {path: null},                             query: "SELECT url as path, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM page__snapshot WHERE route_name = 'page_slug' AND enabled = 1 AND (publication_date_start IS NULL OR publication_date_start <= NOW())" }
#            # product categories
#            - {                 connection: doctrine.dbal.default_connection, route: sonata_catalog_category, parameters: {category_id: null, category_slug: null}, query: "SELECT id as category_id, slug as category_slug, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM classification__category WHERE enabled = true" }
#            # products
            - {                 connection: doctrine.dbal.default_connection, route: backend_article_show,     parameters: {productId: null },            query: "SELECT id as productId,  updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM article" }
    encoding:         UTF-8
    page:
        default: sonata.seo.page.default
        title:            YallaNL Backend
        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             foo bar
                description:          The description
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       YallaNightLife
                    
                'og:description':     A demo of the some rich bundles for your Symfony2 projects
                'og:see_also' :         http://www.yallanightlife.com/
#                'og:url' :
#                'og:image' :
                'og:type' :            website
                'twitter:card':        summary
                'twitter:url' :         http://www.yallanightlife.com/
                'twitter:title' :         http://www.yallanightlife.com/
                'twitter:description': description
            
            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                'Content-Language':     en-us
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"
#            'prefix':
            'itemscope itemtype':    http://schema.org/WebPage
    
    
    
    
    
    
    
    
#    twitter:card– This is the card type. Your options are summary, photo or player. Twitter will default to “summary” if it is not specified.Format:
#    <meta name=”twitter:card” content=”summary”>

#    <meta name=”twitter:url” content=”http://www.nytimes.com/2012/02/19/arts/music/amid-police-presence-fans-congregate-for-whitney-houstons-funeral-in-newark.html”>
#    twitter:title–This is the title of the content to be shared and should be limited to 70 characters after which Twitter will truncate. Again, go for headlines instead of keywords.Format:
#    <meta name=”twitter:title” content=”Parade of Fans for Houston’s Funeral”>
#    twitter:description– This is the description of the content to be shared and should be limited to 200 characters after which Twitter will truncate. Again, go for engaging text, you have more opportunity here than the actual tweet does.Format:
#    <meta name=”twitter:description” content=”NEWARK – The guest list and parade of limousines with celebrities emerging from them seemed more suited to a red carpet event in Hollywood or New York than than a gritty stretch of Sussex Avenue near the former site of the James M. Baxter Terrace public housing project here.”>
#    twitter:image – This is the image that will be displayed on the Twitter Card and it should be a square image no smaller than 60×60 pixels.
#    <meta name=”twitter:image” content=”http://graphics8.nytimes.com/images/2012/02/19/us/19whitney-span/19whitney-span-articleLarge.jpg”>
