ads_manager_show:
    path:   /get/{id}
    defaults:  { _controller: YallaWebsiteBackendBundle:AdsManager:display }

ads_manager_add:
    path:   /add/new/{id}
    defaults:  { _controller: YallaWebsiteBackendBundle:AdsManager:index }
    
ads_manager_save:
    path:   /update/
    defaults:  { _controller: YallaWebsiteBackendBundle:AdsManager:modify }
    