ads_manager_show:
    path:   /{id}
    defaults:  { _controller: YallaWebsiteBackendBundle:AdsManager:display }

ads_manager_save:
    path:   /add/new
    defaults:  { _controller: YallaWebsiteBackendBundle:AdsManager:add }
    
ads_manager_save:
    path:   /update
    defaults:  { _controller: YallaWebsiteBackendBundle:AdsManager:modify }
    