yalla_website_frontend_homepage:
    path:     /main
    defaults: { _controller: YallaWebsiteFrontendBundle:Default:index }

yalla_website_frontend_page_about:
    path:     /page/about
    defaults: { _controller: YallaWebsiteFrontendBundle:Default:about }

yalla_website_frontened_venues:
    path: /guides
    defaults: { _controller: YallaWebsiteFrontendBundle:Default:venues }

yalla_website_frontened_articles:
    path: /gossips
    defaults: { _controller: YallaWebsiteFrontendBundle:Default:articles }

yalla_website_frontened_article:
    path: /gossip/{id}
    defaults: { _controller: YallaWebsiteFrontendBundle:Default:getArticleBySlug }

ads_manager:
    resource: "@YallaWebsiteFrontendBundle/Resources/config/ads_manager_routing.yml"
    prefix:   /ads_manager
    
social_media_follow_us:
    path:     /template/social_media
    defaults: { _controller: YallaWebsiteFrontendBundle:Template:social }