yalla_website_backend_homepage:
    path:     /
    defaults: { _controller: YallaWebsiteBackendBundle:Default:index }

Venues:
    resource: "@YallaWebsiteBackendBundle/Resources/config/venues_routing.yml"
    prefix:   /venue
Events:
    resource: "@YallaWebsiteBackendBundle/Resources/config/events_routing.yml"
    prefix:   /event
Gallery:
    resource: "@YallaWebsiteBackendBundle/Resources/config/gallery_routing.yml"
    prefix:   /gallery
Article:
    resource: "@YallaWebsiteBackendBundle/Resources/config/article_routing.yml"
    prefix:   /article
User:
    resource: "@YallaWebsiteBackendBundle/Resources/config/user_routing.yml"
    prefix:   /user
    
Profile:
    resource: "@YallaWebsiteBackendBundle/Resources/config/profile_routing.yml"
    prefix:   /profile